id: ADE547E97
title: '6833'
type: translation
source_metadata:
  languages:
  - mon
  - sa
  - zh
  - en
  - bo
  - fr
  datatype: PlainText
  created_at: 2022-06-29 16:12:45.208897
  last_modified_at: 2022-06-29 16:12:45.208922
