id: ADE547E97
title: '6833'
type: translation
source : https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
source_metadata:
  creation_method: web_scrapping
  title: Śāntideva: Bodhicaryāvatāra
  languages:
  - mon
  - sa
  - zh
  - en
  - bo
  - fr
  datatype: PlainText
  created_at: 2022-06-29 16:12:45.208897
  last_modified_at: 2022-06-29 16:12:45.208922
